######################################
#  _____ _             _____ ____    #
# |_   _(_)_ __  _   _|___ /|  _ \   #
#   | | | | '_ \| | | | |_ \| | | |  #
#   | | | | | | | |_| |___) | |_| |  #
#   |_| |_|_| |_|\__, |____/|____/   #
#                |___/               #
# Author: Max Bebök                  #
# License: MIT                       #
######################################

BUILD_DIR=build
SOURCE_DIR=src/t3d

include $(N64_INST)/include/n64.mk

src := src/t3d/t3d.c src/t3d/t3dmath.c src/t3d/t3dmodel.c \
	src/t3d/t3ddebug.c src/t3d/t3dskeleton.c src/t3d/t3danim.c \
	src/t3d/rsp/rsp_tiny3d.S

# N64_CFLAGS += -std=gnu2x -DNDEBUG
N64_CFLAGS += -std=gnu2x -Os -Isrc

OBJ = $(BUILD_DIR)/t3dmath.o $(BUILD_DIR)/t3d.o \
	$(BUILD_DIR)/t3dmodel.o $(BUILD_DIR)/t3ddebug.o $(BUILD_DIR)/t3dskeleton.o $(BUILD_DIR)/t3danim.o \
	$(BUILD_DIR)/rsp/rsp_tiny3d.o

all: $(BUILD_DIR)/t3d.a

# Static Library
$(BUILD_DIR)/t3d.a: $(OBJ)
	@mkdir -p $(dir $@)
	@echo "    [LD_LIB] $<"
	$(N64_LD) -r -o $(BUILD_DIR)/t3d.a $^

# RSP metadata
$(SOURCE_DIR)/rsp/rsp_tiny3d.h: $(BUILD_DIR)/rsp/rsp_tiny3d.o
	@echo "    [RSP_METADATA] $<"
	echo "// NOTE: this file is autogenerated by the Makefile of t3d!" > $(SOURCE_DIR)/rsp/rsp_tiny3d.h
	$(N64_GCCPREFIX_TRIPLET)objdump -S -t $(BUILD_DIR)/rsp/rsp_tiny3d.elf \
		| grep .data | grep -v emux \
		| awk '{print "#define", "RSP_T3D_" $$5, "0x" $$1;}' \
		>> $(SOURCE_DIR)/rsp/rsp_tiny3d.h

$(BUILD_DIR)/t3d.o: $(SOURCE_DIR)/rsp/rsp_tiny3d.h

# Sources
$(BUILD_DIR)/%.o: src/t3d/%.c
	@mkdir -p $(dir $@)
	@echo "    [CC_LIB] $<"
	$(N64_CC) -c $(CFLAGS) $(N64_CFLAGS) -o $@ $<

# Runs all demos after each other in the given emulator
run_examples:
	$(EMU_PATH) examples/00_quad/*.z64
	$(EMU_PATH) examples/01_model/*.z64
	$(EMU_PATH) examples/02_lighting/*.z64
	$(EMU_PATH) examples/03_objects/*.z64
	$(EMU_PATH) examples/04_dynamic/*.z64
	$(EMU_PATH) examples/05_splitscreen/*.z64
	$(EMU_PATH) examples/06_offscreen/*.z64
	$(EMU_PATH) examples/07_skeleton/*.z64
	$(EMU_PATH) examples/09_anim_viewer/*.z64
	$(EMU_PATH) examples/99_testscene/*.z64

clean:
	rm -rf $(BUILD_DIR)
	rm -f $(SOURCE_DIR)/rsp/rsp_tiny3d.h

-include $(wildcard $(BUILD_DIR)/*.d)

.PHONY: all clean
